#!/bin/sh

docdir=$(realpath $1)/usr/share/doc/ucf
packfiles="changelog examples/postinst"

mkdir -p $(realpath $1)
git archive master | tar -x -C $(realpath $1)

for f in $packfiles; do
    gzip $docdir/$f;
done

for d in $(find $(realpath $1) -type d -name 'man[1-9]'); do
    for f in $(ls $d); do gzip $d/$f; done;
done

